const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(__dirname+'/web/app.js','utf8');
const context={esc:v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))};
vm.runInNewContext(source.slice(source.indexOf('const displayLabels='),source.indexOf('function renderDiffs('))+'\nglobalThis.test={formatValue,displayScalar,isReview,isError,fieldGroup,longText};',context);
const {formatValue,displayScalar,isReview,isError,fieldGroup,longText}=context.test;
assert.equal(displayScalar(null),'未取得');assert.equal(displayScalar(true),'有');assert.equal(displayScalar(false),'無');
assert.equal(displayScalar(12000,'management_fee'),'12,000円');assert.equal(displayScalar('442.54','area'),'442.54㎡');
assert.equal(displayScalar('2026-01-31'),'2026年1月31日');assert.equal(displayScalar('１２３','area'),'１２３');
const floors=[{floor:'1階',area:442.54},{階:'2階',面積:249.79}];
const before=JSON.stringify(floors),html=formatValue(floors,'floor_areas');
assert(html.includes('<table'));assert(html.includes('442.54㎡'));assert(html.includes('249.79㎡'));assert.equal(JSON.stringify(floors),before);
assert(formatValue([{location:'試験町',lot_number:'1番',area:100.5,numerator:1,denominator:2}],'lands').includes('1／2'));
const mortgage=formatValue([{rank:{value:1},kind:{value:'抵当権'},amount:{value:12000000},debtor:'試験債務者',mortgagee:'試験銀行',active:false}],'mortgages');
assert(mortgage.includes('12,000,000円'));assert(mortgage.includes('無'));assert(mortgage.includes('試験銀行'));
assert(!formatValue([{value:'a'},{value:null}]).includes('[object Object]'));
assert(!formatValue('<img src=x onerror=alert(1)>').includes('<img'));
assert(longText('長文'.repeat(100)).includes('全文を見る'));assert(!longText('短文').includes('data-expand'));
assert(isReview({confidence:.6}));assert(isReview({source_mismatch:true}));assert(!isReview({confidence:.99}));assert(isError({error_message:'test'}));
assert.equal(fieldGroup({type:'registry'},{code:'land_lots'}),'lands');assert.equal(fieldGroup({type:'registry'},{code:'active_mortgages'}),'rights');assert.equal(fieldGroup({type:'important_report'},{code:'building_name'}),'report');
console.log('PASS: tables, units, Japanese dates, null/boolean, character preservation, escaping, expand control, review/error states, grouping, immutable data');
