const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const elements=new Map(),handlers={};const el=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',textContent:'',addEventListener(k,f){handlers[k]=f},showModal(){this.open=true},close(){this.open=false}});return elements.get(id)};
let reads=0,ai=0;const initial={mode:'demo',public_demo:false,cases:[],unmatched:[]};
const saved={id:'saved',building_name:'TEST',unit_name:'101',documents:[],diffs:[],diff_count:0};
const ctx={document:{querySelector:el},window:{addEventListener(){}},fetch:async(url,opt)=>{if(url==='/api/state')return new Promise(()=>{});if(url==='/api/prepare-documents')return {ok:true,json:async()=>({token:'p',ai_files:ai,estimate_jpy:ai?12:0,files:[]})};assert.equal(url,'/api/upload-documents');reads++;return {ok:true,json:async()=>({case_id:'saved',state:{...initial,cases:[saved]}})}},URLSearchParams,location:{hash:'#new'},console,crypto:require('crypto').webcrypto,FormData,Uint8Array};
vm.runInNewContext(fs.readFileSync('web/app.js','utf8')+`
globalThis.ui={addPdfs,processUpload,setState:s=>state=s,reset:()=>{selectedPdfs=[];fileKinds=[];pdfHashes=[];costPlan=null;costApproved=false;},busy:()=>uploadBusy};`,ctx);ctx.ui.setState(initial);
const pdf=()=>new File(['%PDF-fixture'],'建物.pdf',{type:'application/pdf'});
(async()=>{await ctx.ui.addPdfs([pdf()]);assert.equal(reads,1);assert.equal(ctx.location.hash,'#case=saved&tab=excel');ctx.ui.reset();ctx.location.hash='#new';saved.diff_count=1;saved.diffs=[{id:"d",label:"管理費",code:"management_fee",old_value:1,new_value:2,review_status:"unreviewed",can_adopt:true}];await ctx.ui.addPdfs([pdf()]);assert.equal(ctx.location.hash,'#case=saved&tab=review');reads=1;saved.diff_count=0;saved.diffs=[];ctx.ui.reset();ctx.location.hash='#new';ai=1;const pending=ctx.ui.addPdfs([pdf()]);for(let i=0;i<20&&!el('#ai-confirm').open;i++)await new Promise(r=>setImmediate(r));assert(el('#ai-confirm').open);assert.equal(reads,1);el('#ai-cancel').onclick();await pending;assert.equal(reads,1);assert(!ctx.ui.busy());const retry=ctx.ui.processUpload(null);assert(el('#ai-confirm').open);el('#ai-start').onclick();await retry;assert.equal(reads,2);assert.equal(ctx.location.hash,'#case=saved&tab=excel');console.log('PASS: drop automatically reads and advances; AI asks once; cancellation makes no read; consent advances');})().catch(e=>{console.error(e);process.exitCode=1});
