'use strict';
const registrationPreviews=new Map();
let state,csrf,pending;let selectedPdfs=[],fileKinds=[],caseFilter='all',caseSearch='';let filters={document:'all',review:false};const results=new Map();
const view=document.querySelector('#view');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const val=v=>v===null||v===undefined||v===''?'未取得':Array.isArray(v)?v.map(val).join('、'):typeof v==='object'?Object.entries(v).map(([k,x])=>k+'：'+val(x)).join('、'):typeof v==='boolean'?(v?'有':'無'):String(v);
const date=v=>esc(displayScalar(v));
const pill=(text,warn=false)=>`<span class="pill ${warn?'warn':''}">${esc(text)}</span>`;
const route=()=>new URLSearchParams(location.hash.slice(1));
const href=(id,tab='detail')=>`#case=${encodeURIComponent(id)}&tab=${tab}`;
const docLabel=t=>t==='registry'?'謄本':t==='management_rules'?'管理規約':'重調';
const docName=d=>{const name=(d.filename||'').split(/[\\/]/).pop();return !name||/\.json$/i.test(name)?docLabel(d.type)+'（解析済み資料）':name;};
function error(e){document.querySelector('#error').textContent=e.message||String(e)}
async function api(path,body){if(window.PublicDemo)return window.PublicDemo.request(path,body);const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'処理に失敗しました。');return d;}
const steps=[['detail','① 物件・資料'],['registry','② 内容確認'],['review','③ 要確認・差分'],['excel','④ Excel生成']];
const fields=c=>c.documents.flatMap(d=>d.fields.map(f=>({d,f})));
const missing=f=>unwrap(f.value)===null||unwrap(f.value)===undefined||unwrap(f.value)==='';
const needs=f=>missing(f)||isReview(f)||isError(f);
const reviewCount=c=>fields(c).filter(({f})=>needs(f)).length+(c.source_conflicts?.length||0);
function nextWork(c){if(c.registration_required||c.pending_documents?.length)return ['案件・資料の登録','detail'];if(c.generation_blocked)return ['生成不可・資料を確認','detail'];if(results.has(c.id))return ['Excel生成済み','excel'];if(!c.documents.length)return ['資料を追加','detail'];const n=reviewCount(c)+(c.diff_count||0);return n?['要確認 '+n+'件','review']:['読取内容を確認','registry'];}
function stepNav(id,tab){const active=['lands','rights','report','rules','documents'].includes(tab)?'registry':tab==='diffs'?'review':tab;return `<nav class="steps" aria-label="契約書作成の工程">${steps.map(([k,t])=>`<a ${active===k?'aria-current="step"':''} href="${id?href(id,k):'#new'}" class="${active===k?'active':''}">${t}</a>`).join('')}</nav>`;}
function render(){
 if(!state)return;
 document.querySelector('#mode').innerHTML=pill(state.mode==='demo'?'デモ':'業務モード');
 document.querySelector('#notice').textContent=state.public_demo?'公開デモ：架空のサンプルです。操作結果は再読込で戻ります。PDF読取・Excel生成はローカル版で利用できます。':state.mode==='demo'?(state.db_write_enabled?'デモ表示・実データ更新有効：採用操作は保存されます。':'デモモード：解析済み資料を利用します。採用・保留は起動中のみ有効です。'):'';
 document.querySelector('#usage').textContent='';
 const page=route();if(page.has('settings'))return renderInfo('settings');if(page.has('help'))return renderInfo('help');
 if(page.has('new')){view.innerHTML='<h1>新規契約書作成</h1>'+stepNav(null,'detail')+'<section id="panel"></section>';return renderDetail(null,document.querySelector('#panel'));}
 const id=page.get('case');if(!id)return renderList();
 const c=state.cases.find(c=>c.id===id);if(!c){view.innerHTML='<p class="empty">案件が見つかりません。</p>';return;}
 const tab=page.get('tab')||'detail';
 view.innerHTML=`<p class="muted"><a href="#">案件</a> / ${esc(c.building_name)}</p><div class="top"><h1>${esc(c.building_name)} <small>${esc(c.unit_name||'')}</small></h1>${pill(c.status,c.generation_blocked)}</div>${stepNav(c.id,tab)}${c.upload_warnings?.length?`<div class="upload-warning" role="alert">${c.upload_warnings.map(x=>`<p>${esc(x)}</p>`).join('')}</div>`:''}<section id="panel"></section>`;
 const panel=document.querySelector('#panel');
 if(['documents','registry','lands','rights','report','rules'].includes(tab)){filters.group=({documents:'basic',registry:'basic',lands:'landrights',rights:'landrights',report:'report',rules:'rules'})[tab];renderDocuments(c,panel);}else if(['diffs','review'].includes(tab))renderReview(c,panel);else if(tab==='excel')renderExcel(c,panel);else renderDetail(c,panel);
}
function renderInfo(page){view.innerHTML=page==='settings'?`<h1>設定</h1><div class="card"><h2>利用環境</h2><p>現在：${state.public_demo?'公開デモ':state.mode==='demo'?'ローカルデモ':'業務モード'}</p><p>ひな形：区分マンション用</p><p>接続・ひな形の設定変更は管理者が行います。</p><a href="#">案件に戻る</a></div>`:`<h1>ヘルプ</h1><div class="card"><ol><li>新規契約書作成から同じ物件の謄本PDFを選択します。</li><li>物件・所有者・面積を確認します。根拠は各行で開けます。</li><li>要確認と新旧差分を確認し、採用・保留を選びます。</li><li>Excelを生成し、ダウンロード後に内容を確認します。</li></ol><p>デモでは解析済みの同一PDFのみ使用できます。重調・管理規約も一緒に選択でき、案件登録後に保存します。</p><p>公開デモではPDF送信・Excel生成は利用できません。</p><a href="#">案件に戻る</a></div>`;}
function renderList(){const cases=state.cases.filter(c=>(caseFilter==='all'||(caseFilter==='done')===results.has(c.id))&&((c.building_name||'')+' '+(c.unit_name||'')).includes(caseSearch));view.innerHTML=`<div class="top"><h1>案件</h1><a class="button primary" href="#new">新規契約書作成</a></div><div class="toolbar"><label>表示 <select id="case-filter"><option value="all">すべて</option><option value="working" ${caseFilter==='working'?'selected':''}>作成中</option><option value="done" ${caseFilter==='done'?'selected':''}>作成済み（この画面で生成）</option></select></label><label>物件名・号室 <input id="case-search" type="search" value="${esc(caseSearch)}" placeholder="案件を検索"></label><button data-action="refresh">一覧を更新</button></div><div class="card table-scroll"><table><thead><tr><th>物件名</th><th>号室</th><th>現在の作業</th><th>要確認</th><th>最終更新</th><th></th></tr></thead><tbody>${cases.map(c=>{const [label,tab]=nextWork(c);return `<tr class="case-row"><td><a href="${href(c.id)}">${esc(c.building_name)}</a></td><td>${esc(c.unit_name||'未取得')}</td><td>${esc(label)}</td><td>${reviewCount(c)}件${c.diff_count?'・差分 '+c.diff_count+'件':''}</td><td>${date(c.updated_at)}</td><td><a href="${href(c.id,tab)}">続きから</a></td></tr>`}).join('')}</tbody></table>${cases.length?'':'<p class="empty">該当する案件はありません。</p>'}</div><p class="muted">作成済みは、この画面を開いてからExcelを生成した案件です。内容確認・契約締結の完了を意味しません。</p>${state.unmatched.length?`<p>住戸未照合の資料：${state.unmatched.length}件</p>`:''}`;}
function selectedFiles(){return selectedPdfs.map((f,i)=>`<tr><td>${esc(f.name)}</td><td><select aria-label="${esc(f.name)}の資料種類" data-kind="${i}"><option value="unknown" ${fileKinds[i]==='unknown'?'selected':''}>資料種類を選択</option><option value="registry" ${fileKinds[i]==='registry'?'selected':''}>謄本（建物・土地）</option><option value="report" ${fileKinds[i]==='report'?'selected':''}>重調</option><option value="rules" ${fileKinds[i]==='rules'?'selected':''}>管理規約</option></select></td><td>未読取・種類を確認</td></tr>`).join('');}
function renderDetail(c,p){p.innerHTML=`<div class="card"><h2>物件・資料</h2><p>対象：区分マンション</p><dl class="facts">${[['案件名',c?c.building_name+' '+(c.unit_name||''):'読取後に確認'],['物件名',c?.building_name||'読取後に確認'],['号室',c?.unit_name||'読取後に確認']].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><h3>資料</h3><p>同一住戸の建物・土地謄本をまとめて選択してください。取込後、登録前の照合結果を確認します。</p><p class="muted">謄本・重調・管理規約をまとめて選択できます。資料種類を確認してください。重調・規約は案件登録後に読み取り、確定した住戸・建物へ保存します。</p><input id="registry-pdfs" type="file" accept=".pdf,application/pdf" multiple hidden ${state.public_demo?'disabled':''}><div class="table-scroll"><table><thead><tr><th>ファイル名</th><th>資料種類</th><th>状態</th></tr></thead><tbody>${c?c.documents.flatMap(d=>(d.source_files?.length?d.source_files:[docName(d)]).map(name=>`<tr><td>${esc(name||'資料名未取得')}</td><td>${docLabel(d.type)}</td><td>読取済</td></tr>`)).join(''):''}</tbody><tbody id="selected-files">${selectedFiles()}</tbody></table></div><div class="actions step-actions"><a class="button" href="#">戻る</a><button data-action="select-pdf" ${state.public_demo?'disabled':''}>${c?'資料を追加':'PDFを選択'}</button><button class="primary" data-action="read-next" ${state.public_demo&&!c?'disabled':''}>${selectedPdfs.length?'読み取る':c?'内容確認へ':'読み取る'}</button><span id="upload-status" role="status"></span></div>${state.public_demo?'<p>PDF追加はローカル版で利用できます。</p>':'<p class="muted">デモモードでは解析済みPDFを再利用し、新たなAI解析は行いません。</p>'}</div>`;if(c&&c.id.startsWith('upload-'))p.innerHTML+=registrationPanel(c);if(c?.pending_documents?.length)p.innerHTML+=pendingPanel(c);}
const displayLabels={floor:'階',階:'階',area:'面積',面積:'面積',location:'所在',lot_number:'地番',land_category:'地目',land_area:'地積',right_type:'権利',share:'持分',numerator:'分子',denominator:'分母',rank:'順位',rank_number:'順位',type:'種類',amount:'債権額',debt_amount:'債権額',debtor:'債務者',debtors:'債務者',mortgagee:'抵当権者',creditor:'抵当権者',active:'有効',name:'氏名・名称',address:'住所',company_number:'会社法人等番号',value:'値'};
const unwrap=v=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.hasOwn(v,'value')?v.value:v;
const pick=(row,...keys)=>{for(const k of keys)if(row&&Object.hasOwn(row,k))return unwrap(row[k]);return null;};
const isReview=f=>Boolean(f.needs_review||f.evidence_mismatch||f.source_mismatch||f.source_consistent===false||(typeof f.confidence==='number'&&f.confidence<.85));
const isError=f=>Boolean(f.error||f.error_message||f.status==='error'||f.evidence_mismatch||f.source_mismatch||f.source_consistent===false);
function displayScalar(input,code=''){
 const v=unwrap(input);if(v===null||v===undefined||v==='')return '未取得';if(typeof v==='boolean')return code==='active'?(v?'有効':'無効'):(v?'有':'無');
 const text=String(v),d=text.match(/^(\d{4})-(\d{2})(?:-(\d{2}))?(?:T.*)?$/);
 if(d)return `${d[1]}年${Number(d[2])}月${d[3]?Number(d[3])+'日':''}`;
 const money=/fee$|amount|債権額|金額|月額|極度額/.test(code),area=/area$|面積|地積/.test(code);
 if(typeof v==='number'||/^\d+(?:\.\d+)?$/.test(text)){
  const n=Number(v),digits=(text.split('.')[1]||'').length;
  const formatted=['house_number','lot_number','unit_name','rank'].includes(code)?text:n.toLocaleString('ja-JP',{maximumFractionDigits:Math.min(20,digits),minimumFractionDigits:Math.min(20,digits)});
  return formatted+(money?'円':area?'㎡':code==='total_units'?'戸':code==='unit_name'?'号室':code==='floor'||code==='unit_floor'?'階':'');
 }
 return text;
}
function longText(text){const more=text.length>85||text.split('\n').length>3;return `<div class="long-copy"><div class="${more?'clamped':''}">${esc(text)}</div>${more?'<button type="button" class="expand-text" data-expand aria-expanded="false">全文を見る</button>':''}</div>`;}
function shareValue(row){const share=pick(row,'share','right_share','持分','権利の割合');if(share!==null)return share;const n=pick(row,'numerator','share_numerator','持分_分子'),d=pick(row,'denominator','share_denominator','持分_分母');return n!==null&&d!==null?`${n}／${d}`:null;}
function valueTable(rows,columns,label){return `<div class="value-table-wrap"><table class="value-table" aria-label="${esc(label)}"><thead><tr>${columns.map(c=>`<th scope="col">${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${columns.map(([name,key,get])=>`<td>${formatValue(get(row),key)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function formatValue(input,code=''){
 const v=unwrap(input);
 if(Array.isArray(v)){
  if(!v.length)return '<span class="muted">該当なし</span>';
  const rows=v.map(unwrap);
  if(code==='floor_areas')return valueTable(rows,[['階','floor',r=>pick(r,'floor','階')],['面積','area',r=>pick(r,'area','面積','各階面積')]],'各階床面積');
  if(['lands','land_lots'].includes(code))return valueTable(rows,[['所在','location',r=>pick(r,'location','所在')],['地番','lot_number',r=>pick(r,'lot_number','地番')],['地目','land_category',r=>pick(r,'land_category','category','地目')],['地積','area',r=>pick(r,'area','land_area','地積')],['権利','right_type',r=>pick(r,'right_type','権利','権利の種類')],['持分','share',shareValue]],'土地一覧');
  if(['mortgages','active_mortgages'].includes(code))return valueTable(rows,[['順位','rank',r=>pick(r,'rank','rank_number','順位','順位番号')],['種類','type',r=>pick(r,'type','kind','種類')],['債権額','amount',r=>pick(r,'amount','debt_amount','債権額','極度額')],['債務者','debtor',r=>pick(r,'debtor','debtors','債務者')],['抵当権者','mortgagee',r=>pick(r,'mortgagee','creditor','抵当権者')],['状態','active',r=>pick(r,'active','有効','現在有効')]],'抵当権一覧');
  if(rows.every(x=>x&&typeof x==='object'&&!Array.isArray(x))){const keys=[...new Set(rows.flatMap(Object.keys))];return valueTable(rows,keys.map(k=>[displayLabels[k]||k,k,r=>r[k]]),'一覧');}
  return `<ul class="value-list">${rows.map(x=>`<li>${formatValue(x)}</li>`).join('')}</ul>`;
 }
 if(v&&typeof v==='object')return `<dl class="object-values">${Object.entries(v).map(([k,x])=>`<div><dt>${esc(displayLabels[k]||k)}</dt><dd>${formatValue(x,k)}</dd></div>`).join('')}</dl>`;
 return longText(displayScalar(v,code));
}
const documentGroups=[['basic','基本情報'],['lands','土地'],['rights','権利・抵当権'],['report','重調'],['review','要確認のみ']];
function fieldGroup(d,f){if(d.type==='management_rules')return 'rules';if(d.type==='important_report')return 'report';if(['land_lots','lands'].includes(f.code))return 'lands';if(/mortgage|land_right|leasehold|tenure/.test(f.code))return 'rights';return 'basic';}
function fieldStatus(f){return isError(f)?'根拠不一致・エラー':missing(f)?'未取得':isReview(f)?'要確認':f.approved?'✓ 確認済':'読取済';}
function evidenceRow(d,f){return `<details class="evidence-toggle"><summary>根拠</summary><div class="evidence-body"><strong>${esc(docName(d))}</strong><p>ページ：${esc(f.page_no??'未取得')} ／ 基準日：${esc(displayScalar(f.value_as_of_date))}</p>${f.source_article?`<p>条文：${esc(f.source_article)}</p>`:''}${f.source_section?`<p>${esc(f.source_section)}</p>`:''}${longText(f.source_text||'根拠テキスト未取得')}${f.candidates?.length?`<details><summary>条文候補 ${f.candidates.length}件（適用条件を確認）</summary>${f.candidates.map(x=>`<p>${esc(x.source_article)} ／ ${esc(x.page_no)}ページ</p>${longText(x.source_text)}`).join('')}</details>`:''}${f.error_message?longText(f.error_message):''}</div></details>`;}
function fieldRows(rows){return `<div class="field-head"><span>項目</span><span>値</span><span>状態</span></div>${rows.map(({d,f})=>`<article class="document-field ${isError(f)?'field-error':needs(f)?'field-review':f.approved?'field-approved':''}"><div class="field-label"><h3>${esc(f.label)}</h3></div><div class="field-value">${formatValue(f.value,f.code)}</div><div class="field-state">${pill(fieldStatus(f),needs(f))}${!f.excel_supported?'<small>Excel未対応</small>':''}${evidenceRow(d,f)}</div></article>`).join('')}${rows.length?'':'<p class="empty">該当する項目はありません。</p>'}`;}
function renderDocuments(c,p){const group=filters.group||'basic';const rows=fields(c).filter(({d,f})=>group==='landrights'?['lands','rights'].includes(fieldGroup(d,f)):fieldGroup(d,f)===group).filter(({d,f})=>(filters.document==='all'||d.version_id===filters.document)&&(!filters.review||needs(f)));p.innerHTML=`<div class="card document-card"><h2>読取内容の確認</h2><p class="next-task">次の作業：物件・所有者・面積を確認してください</p><nav class="document-tabs" aria-label="確認する情報">${[['registry','basic','建物・住戸'],['lands','landrights','土地・権利'],['report','report','管理・費用'],['rules','rules','管理規約']].map(([t,g,label])=>`<a class="button ${group===g?'selected':''}" href="${href(c.id,t)}" ${group===g?'aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="toolbar"><label>資料 <select id="document-filter"><option value="all">すべての資料</option>${c.documents.map(d=>`<option value="${esc(d.version_id)}" ${filters.document===d.version_id?'selected':''}>${esc(docName(d))}</option>`).join('')}</select></label><label><input id="review-filter" type="checkbox" ${filters.review?'checked':''}> 要確認のみ</label></div>${fieldRows(rows)}<div class="actions step-actions"><a class="button" href="${href(c.id)}">戻る</a><a class="button primary" href="${href(c.id,'review')}">要確認・差分へ</a></div></div>`;}
function renderReview(c,p){const all=fields(c).filter(({f})=>needs(f));const buckets=[['根拠不一致・エラー',({f})=>isError(f)],['未取得',({f})=>!isError(f)&&missing(f)],['読み取りの確かさを確認',({f})=>!isError(f)&&!missing(f)&&typeof f.confidence==='number'&&f.confidence<.85],['その他の要確認',({f})=>!isError(f)&&!missing(f)&&!(typeof f.confidence==='number'&&f.confidence<.85)]];p.innerHTML=`<div class="card"><h2>要確認・差分</h2><p>要確認 ${all.length+(c.source_conflicts?.length||0)}件 ／ 未確認差分 ${c.diff_count||0}件</p>${c.pending_documents?.length?'<p class="upload-warning">未保存の追加資料があります。物件・資料で保存を完了してください。</p>':''}${c.registration_required?'<p class="upload-warning">物件・資料で登録前の確認を行い、「この案件で登録」を押してください。</p>':''}<p>${c.generation_blocked?'生成不可：資料・物件の確認が必要です。':'要確認を確認してください。生成可否は既存の判定に従います。'}</p>${buckets.map(([label,test])=>{const rows=all.filter(test);return rows.length?`<details ${label==='根拠不一致・エラー'?'open':''} class="review-section"><summary>${label}（${rows.length}件）</summary>${fieldRows(rows)}</details>`:''}).join('')}${results.get(c.id)?.warnings?.length?`<details open><summary>生成前に確認が必要な項目</summary><ul>${results.get(c.id).warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul></details>`:''}${conflictPanel(c)}<h3>新旧差分</h3><div id="diff-panel"></div><div class="actions step-actions"><a class="button" href="${href(c.id,'registry')}">内容確認へ戻る</a><a class="button primary" href="${href(c.id,'excel')}">契約書生成へ</a></div></div>`;renderDiffs(c,document.querySelector('#diff-panel'));}
function renderDiffs(c,p){p.innerHTML=`<h2>変更候補を確認</h2><p class="muted">採用するまで確定値は変更されません。保留した差分は、後から再確認できます。</p>${c.diffs.map(d=>`<div class="card"><div class="top"><div><h3>${esc(d.label)}</h3></div>${pill(({unreviewed:'未確認',reviewed:'保留',applied:'採用済み',ignored:'対象外'})[d.review_status]||d.review_status,d.review_status!=='applied')}</div><div class="diff-values"><div><span class="muted">旧</span><p>${formatValue(d.old_value,d.code)}</p></div><span>→</span><div class="new"><span class="muted">新</span><p>${formatValue(d.new_value,d.code)}</p></div></div><p class="muted">${esc(d.source||'根拠資料の確認が必要')}</p><div class="actions"><button class="primary" data-action="adopt" data-diff="${esc(d.id)}" ${!d.can_adopt||['applied','ignored'].includes(d.review_status)?'disabled':''}>採用</button><button data-action="hold" data-diff="${esc(d.id)}" ${['applied','ignored'].includes(d.review_status)?'disabled':''}>保留</button>${!d.can_adopt?'<span class="muted">根拠確認が必要なため採用できません</span>':''}</div></div>`).join('')}${!c.diffs.length?'<div class="card empty">差分はありません。</div>':''}`;}
function renderExcel(c,p){const r=results.get(c.id),unsupported=fields(c).filter(({f})=>!f.excel_supported);p.innerHTML=`<div class="card"><h2>契約書生成</h2><p>対象：${esc(c.building_name)} ${esc(c.unit_name||'')}</p><p>ひな形：区分マンション用</p><dl class="facts"><div><dt>自動反映</dt><dd>${r?`謄本 ${r.registry_written??0}セル・重調 ${r.report_written??0}項目`:'生成後に実績を表示'}</dd></div><div><dt>要確認</dt><dd>${reviewCount(c)}件${c.diff_count?'・差分 '+c.diff_count+'件':''}</dd></div><div><dt>Excel未対応</dt><dd>${unsupported.length}項目</dd></div></dl><details><summary>Excel未対応の項目を見る</summary><ul>${unsupported.map(({f})=>`<li>${esc(f.label)}</li>`).join('')}</ul><p>保存済みの値は内容確認で確認できます。</p></details>${c.pending_documents?.length?'<p class="upload-warning">未保存の追加資料があります。物件・資料で保存を完了してください。</p>':''}${c.registration_required?'<p class="upload-warning">物件・資料で登録前の確認を行い、「この案件で登録」を押してください。</p>':''}${c.generation_blocked?'<p class="upload-warning">生成不可：戸建て・物件種別不明・資料間不一致は確認が必要です。</p>':state.public_demo?'<p>Excel生成はローカル版で利用可能です。公開デモでは生成・ダウンロードできません。</p>':state.mode==='demo'?'<p class="pill warn">デモ出力です。使用前に内容を確認してください。</p>':''}${r?`<div class="success"><strong>生成・再読込確認が完了しました</strong><p>${esc(r.filename)}</p></div>${r.warnings?.length?`<details open class="review-section"><summary>出力の要確認事項（${r.warnings.length}件）</summary><ul>${r.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul></details>`:''}`:''}<div class="actions step-actions"><a class="button" href="${href(c.id,'review')}">確認へ戻る</a><button class="${r?'':'primary'}" data-action="generate" ${state.public_demo||c.generation_blocked||c.registration_required||c.pending_documents?.length?'disabled':''}>${r?'Excelを再生成':'Excelを生成'}</button>${r?`<a class="button primary" href="${esc(r.download)}" download>ダウンロード</a>`:''}</div></div>`;}

function registrationPanel(c){const r=registrationPreviews.get(c.id);return `<div class="card"><h2>案件のDB登録</h2><p>登録前に物件・住戸・所有者と既存候補を確認してください。照合だけではDBを書き換えません。</p><button data-action="registration-preview" ${c.generation_blocked?'disabled':''}>登録前の確認・候補を照合</button>${r?`<dl class="facts">${[['building_name','物件名'],['unit_name','号室'],['house_number','家屋番号'],['registry_location','登記所在'],['current_owner_name','所有者']].map(([k,l])=>`<div><dt>${l}</dt><dd>${esc(r.summary[k]??'未取得')}</dd></div>`).join('')}</dl><h3>既存候補</h3>${r.match.candidates?.length?`<div class="table-scroll"><table><thead><tr><th>物件名</th><th>号室</th><th>家屋番号</th><th>所在</th><th>所有者</th></tr></thead><tbody>${r.match.candidates.map(x=>`<tr><td>${esc(x.building_name||'未取得')}</td><td>${esc(x.unit_name||'—')}</td><td>${esc(x.house_number||'—')}</td><td>${esc(x.registry_location||'—')}</td><td>${esc(x.current_owner_name||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<p>候補はありません。</p>'}<p>${esc(r.message||r.match.reason|| (r.match.status==='existing'?'既存住戸へ紐付けます。':'新規の物件・住戸を登録します。'))}</p>${['new','existing'].includes(r.match.status)&&!r.demo?`<label>案件の扱い <select id="registration-case-mode">${r.match.cases.map(x=>`<option value="resume:${esc(x.case_id)}">既存案件を再開（${esc(x.case_status)} / ${esc(x.updated_at||'更新日不明')}）</option>`).join('')}<option value="new">新しい案件を作成</option></select></label><div class="actions"><button class="primary" data-action="register-case">この案件で登録</button></div>`:'<p class="pill warn">要確認：この状態ではDB登録しません。</p>'}`:''}</div>`;}

view.addEventListener('change',e=>{if(e.target.id==='registry-pdfs'){selectedPdfs=Array.from(e.target.files);fileKinds=selectedPdfs.map(f=>/規約|細則/.test(f.name)?'rules':/重調|重要事項調査/.test(f.name)?'report':/謄本|登記|建物|土地/.test(f.name)?'registry':'unknown');render();return;}if(e.target.dataset.kind!==undefined){fileKinds[Number(e.target.dataset.kind)]=e.target.value;return;}if(e.target.id==='case-filter'){caseFilter=e.target.value;renderList();return;}if(e.target.id==='case-search'){caseSearch=e.target.value;renderList();return;}if(!['document-filter','review-filter'].includes(e.target.id))return;if(e.target.id==='document-filter')filters.document=e.target.value;if(e.target.id==='review-filter')filters.review=e.target.checked;render();});
view.addEventListener('click',async e=>{const expand=e.target.closest('[data-expand]');if(expand){const open=expand.getAttribute('aria-expanded')!=='true';expand.setAttribute('aria-expanded',String(open));expand.previousElementSibling.classList.toggle('clamped',!open);expand.textContent=open?'閉じる':'全文を見る';return;}const group=e.target.closest('[data-group]');if(group){filters.group=group.dataset.group;filters.document='all';filters.review=false;render();return;}const b=e.target.closest('button[data-action]');if(!b)return;const action=b.dataset.action,cid=route().get('case');document.querySelector('#error').textContent='';
 if(action==='registration-preview'||action==='register-case'){b.disabled=true;try{if(action==='registration-preview'){registrationPreviews.set(cid,await api('/api/registration-preview',{case_id:cid}));render();}else{const r=registrationPreviews.get(cid),mode=document.querySelector('#registration-case-mode').value;const result=await api('/api/register-case',{token:r.token,case_mode:mode==='new'?'new':'resume',resume_case_id:mode.startsWith('resume:')?mode.slice(7):null});state=result.state;registrationPreviews.delete(cid);location.hash=href(result.case_id,result.warning?'detail':'registry');render();if(result.warning)error(Error(result.warning));}}catch(e){error(e);b.disabled=false;}return;}
 if(action==='retry-documents'){b.disabled=true;try{const result=await api('/api/retry-documents',{case_id:cid});state=result.state;render();if(result.warning)error(Error(result.warning));}catch(e){error(e);b.disabled=false;}return;}
 if(action==='select-pdf'){document.querySelector('#registry-pdfs').click();return;}
 if(action==='read-next'&&!selectedPdfs.length&&cid){location.hash=href(cid,'registry');return;}
 if(action==='upload'||action==='read-next'){if(!selectedPdfs.length||fileKinds.includes('unknown')){error(Error('PDFと各資料種類を選択してください。'));return;}const form=new FormData();for(const f of selectedPdfs)form.append('pdfs',f);form.append('kinds',JSON.stringify(fileKinds));if(cid)form.append('case_id',cid);b.disabled=true;document.querySelector('#upload-status').textContent='資料を取り込み中…';try{const response=await fetch('/api/upload-documents',{method:'POST',headers:{'X-CSRF-Token':csrf},body:form});const result=await response.json();if(!response.ok)throw Error(result.error);state=result.state;selectedPdfs=[];fileKinds=[];location.hash=href(result.case_id,'detail');render();if(result.warning)error(Error(result.warning));}catch(e){error(e);b.disabled=false;const status=document.querySelector('#upload-status');if(status)status.textContent='';}return;}
 if(action==='adopt'){pending={case_id:cid,diff_id:b.dataset.diff,action:'adopt'};const d=state.cases.find(c=>c.id===cid).diffs.find(d=>d.id===b.dataset.diff);document.querySelector('#confirm-text').innerHTML=esc(d.label)+'：<div class=diff-values><div>'+formatValue(d.old_value,d.code)+'</div><span>→</span><div>'+formatValue(d.new_value,d.code)+'</div></div>';document.querySelector('#confirm').showModal();return;}
 b.disabled=true;const old=b.textContent;if(action==='generate')b.textContent='契約書作成中…';
 try{if(action==='generate')results.set(cid,await api('/api/generate',{case_id:cid}));else if(action==='hold')state=await api('/api/decision',{case_id:cid,diff_id:b.dataset.diff,action:'hold'});else if(action==='refresh')state=await api('/api/refresh',{});render();}catch(e){error(e);b.disabled=false;b.textContent=old;}
});
document.querySelector('#cancel').onclick=()=>document.querySelector('#confirm').close();
document.querySelector('#accept').onclick=async()=>{const b=document.querySelector('#accept');b.disabled=true;try{state=await api('/api/decision',pending);results.delete(pending.case_id);document.querySelector('#confirm').close();render();}catch(e){document.querySelector('#confirm').close();error(e)}finally{b.disabled=false}};
window.addEventListener('hashchange',()=>{document.querySelector('#error').textContent='';filters.document='all';filters.review=false;render()});
api('/api/state').then(d=>{state=d;csrf=d.csrf;render()}).catch(error);

function pendingPanel(c){return `<div class="card"><h3>登録待ちの追加資料</h3><table><thead><tr><th>資料名</th><th>種類</th><th>状態</th></tr></thead><tbody>${c.pending_documents.map(f=>`<tr><td>${esc(f.filename)}</td><td>${f.kind==='rules'?'管理規約':'重調'}</td><td>未保存</td></tr>`).join('')}</tbody></table>${!c.registration_required?'<button data-action="retry-documents">追加資料の保存を再実行</button>':'<p>「この案件で登録」の後に読み取り・保存します。</p>'}</div>`;}
function conflictPanel(c){return c.source_conflicts?.length?`<h3>重調と管理規約の記載差（要確認 ${c.source_conflicts.length}件）</h3><table><thead><tr><th>項目</th><th>重調</th><th>管理規約（原本優先）</th><th>状態</th></tr></thead><tbody>${c.source_conflicts.map(x=>`<tr><td>${esc(x.label)}</td><td>${formatValue(x.report_value,x.code)}<p>${esc(x.report_document)}</p></td><td>${formatValue(x.rules_value,x.code)}<p>${esc(x.rules_document)}</p></td><td>要確認<p>${esc(x.reason)}</p></td></tr>`).join('')}</tbody></table>`:'';}
