'use strict';
const registrationPreviews=new Map();
let state,csrf,pending;let selectedPdfs=[],fileKinds=[],caseFilter='all',caseSearch='';let filters={document:'all',review:false};const results=new Map();
const view=document.querySelector('#view');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const val=v=>v===null||v===undefined||v===''?'未取得':Array.isArray(v)?v.map(val).join('、'):typeof v==='object'?Object.entries(v).map(([k,x])=>k+'：'+val(x)).join('、'):typeof v==='boolean'?(v?'有':'無'):String(v);
const date=v=>esc(displayScalar(v));
const pill=(text,warn=false)=>`<span class="pill ${warn?'warn':''}">${esc(text)}</span>`;
const route=()=>new URLSearchParams(location.hash.slice(1));
const href=(id,tab='detail')=>`#case=${encodeURIComponent(id)}&tab=${tab}`;
const docLabel=t=>t==='purchase_important_explanation'?'購入時重説（過去資料）':t==='registry'?'謄本':t==='management_rules'?'管理規約':'重調';
const docName=d=>{const name=(d.filename||'').split(/[\\/]/).pop();return !name||/\.json$/i.test(name)?docLabel(d.type)+'（解析済み資料）':name;};
function error(e){document.querySelector('#error').textContent=e.message||String(e)}
async function api(path,body){if(window.PublicDemo)return window.PublicDemo.request(path,body);const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'処理に失敗しました。');return d;}
const steps=[['detail','① 資料アップ'],['review','② 要確認'],['excel','③ 契約書生成']];
const fields=c=>c.documents.flatMap(d=>d.fields.map(f=>({d,f})));
const missing=f=>unwrap(f.value)===null||unwrap(f.value)===undefined||unwrap(f.value)==='';
const needs=f=>missing(f)||isReview(f)||isError(f);
const importantMissing=new Set(['building_name','unit_name','house_number','registry_location','display_address','current_owner_name','registered_area','built_date','sale_price','handover_date','management_fee','repair_reserve_fee']);
const attention=f=>needs(f)&&(!missing(f)||importantMissing.has(f.code)||f.excel_supported||isError(f));
const unresolvedDiffs=c=>c.diffs.filter(d=>!['applied','ignored'].includes(d.review_status)&&d.user_choice!=='old');
const unresolvedConflicts=c=>(c.source_conflicts||[]).filter(x=>!x.chosen_source);
const reviewCount=c=>unresolvedDiffs(c).length+unresolvedConflicts(c).length;
const blocking=c=>!!(c.generation_blocked||c.registration_required||c.pending_documents?.length);
const afterUpload=c=>!c?'detail':blocking(c)||reviewCount(c)?'review':'excel';
function nextWork(c){if(results.has(c.id))return ['Excel生成済み','excel'];if(!c.documents.length)return ['資料を追加','detail'];return afterUpload(c)==='review'?['要確認 '+(reviewCount(c))+'件','review']:['契約書を生成できます','excel'];}
function stepNav(id,tab){const active=['detail','excel'].includes(tab)?tab:'review';return `<nav class="steps" aria-label="契約書作成の工程">${steps.map(([k,t])=>`<a ${active===k?'aria-current="step"':''} href="${id?href(id,k):'#new'}" class="${active===k?'active':''}">${t}</a>`).join('')}</nav>`;}
function render(){
 if(!state)return;
 document.querySelector('#mode').innerHTML=pill(state.mode==='demo'?'デモ':'業務モード');
 document.querySelector('#notice').textContent=state.public_demo?'公開デモ：架空のサンプルです。操作結果は再読込で戻ります。PDF読取・Excel生成はローカル版で利用できます。':state.mode==='demo'?(state.db_write_enabled?'デモ表示・実データ更新有効：採用操作は保存されます。':'デモモード：解析済み資料を利用します。採用・保留は起動中のみ有効です。'):'';
 document.querySelector('#usage').textContent='';
 const page=route();if(page.has('mapping'))return renderMapping();if(page.has('settings'))return renderInfo('settings');if(page.has('help'))return renderInfo('help');
 if(page.has('new'))return renderNew();

 const id=page.get('case');if(!id){if(page.has('list')){caseFilter=['all','working','done'].includes(page.get('list'))?page.get('list'):'working';return renderList();}return renderHome();}
 const c=state.cases.find(c=>c.id===id);if(!c){view.innerHTML='<p class="empty">案件が見つかりません。</p>';return;}
 const tab=page.get('tab')||'detail';
 view.innerHTML=`<p class="muted"><a href="#">案件</a> / ${esc(c.building_name)}</p><div class="top"><h1>${esc(c.building_name)} <small>${esc(c.unit_name||'')}</small></h1>${pill(c.generation_blocked?'生成不可':results.has(c.id)?'Excel生成済み':'作成中',c.generation_blocked)}</div>${stepNav(c.id,tab)}${analysisSummary(c)}${uploadScope===c.id&&uploadMessage.startsWith('完了')?`<p role="status">${esc(uploadMessage)}</p>`:''}${c.upload_warnings?.length?`<div class="upload-warning" role="alert">${c.upload_warnings.map(x=>`<p>${esc(x)}</p>`).join('')}</div>`:''}<section id="panel"></section>`;
 const panel=document.querySelector('#panel');
 if(tab==='detail')renderDetail(c,panel);else if(tab==='excel')renderExcel(c,panel);else renderReview(c,panel);
}
function renderHome(){view.innerHTML=`<h1>契約書作成</h1><p>この画面でやること：新しく作成するか、作成中の案件を選んでください。</p><div class="actions"><a class="button primary" href="#new">新しい契約書を作成</a><a class="button" href="#list=working">作成中の案件を開く</a><a class="button" href="#list=done">作成済みを見る</a></div>`;}
function renderNew(){view.innerHTML='<h1>新しい契約書を作成</h1>'+stepNav(null,'detail')+'<section id="panel"></section>';renderDetail(null,document.querySelector('#panel'));}
function renderInfo(page){view.innerHTML=page==='settings'?`<h1>設定</h1><div class="card"><h2>設定</h2><a class="button" href="#mapping">Excelマッピング</a><p>現在：${state.public_demo?'公開デモ':state.mode==='demo'?'ローカルデモ':'業務モード'}</p><p>ひな形：区分マンション用</p><p>接続・ひな形の設定変更は管理者が行います。</p><a href="#">案件に戻る</a></div>`:`<h1>ヘルプ</h1><div class="card"><ol><li>「新しい契約書を作成」から同じ物件のPDFを追加します。</li><li>要確認と新旧差分を確認し、採用・保留を選びます。</li><li>Excelを生成し、ダウンロード後に内容を確認します。</li></ol><p>デモでは解析済みの同一PDFのみ使用できます。重調・管理規約も一緒に選択でき、案件登録後に保存します。</p><p>公開デモではPDF送信・Excel生成は利用できません。</p><a href="#">案件に戻る</a></div>`;}
function renderList(){const cases=state.cases.filter(c=>(caseFilter==='all'||(caseFilter==='done')===results.has(c.id))&&((c.building_name||'')+' '+(c.unit_name||'')).includes(caseSearch));view.innerHTML=`<div class="top"><h1>案件</h1><a class="button primary" href="#new">新しい契約書を作成</a></div><div class="toolbar"><label>表示 <select id="case-filter"><option value="all">すべて</option><option value="working" ${caseFilter==='working'?'selected':''}>作成中</option><option value="done" ${caseFilter==='done'?'selected':''}>作成済み（この画面で生成）</option></select></label><label>物件名・号室 <input id="case-search" type="search" value="${esc(caseSearch)}" placeholder="案件を検索"></label><button data-action="refresh">一覧を更新</button></div><div class="card table-scroll"><table><thead><tr><th>物件名</th><th>号室</th><th>次の作業</th><th>要確認</th><th>最終更新</th><th></th></tr></thead><tbody>${cases.map(c=>{const [label,tab]=nextWork(c);return `<tr class="case-row"><td><a href="${href(c.id,tab)}">${esc(c.building_name)}</a></td><td>${esc(c.unit_name||'未取得')}</td><td>${esc(label)}</td><td>${reviewCount(c)}件${c.diff_count?'・差分 '+c.diff_count+'件':''}</td><td>${date(c.updated_at)}</td><td><a href="${href(c.id,tab)}">続きから</a></td></tr>`}).join('')}</tbody></table>${cases.length?'':'<p class="empty">該当する案件はありません。</p>'}</div><p class="muted">作成済みは、この画面を開いてからExcelを生成した案件です。内容確認・契約締結の完了を意味しません。</p>${state.unmatched.length?`<p>住戸未照合の資料：${state.unmatched.length}件</p>`:''}`;}
let costPlan=null,costApproved=false,costChecking=false;const analysisResults=new Map();
const costLabel=v=>v===null||v===undefined?'概算不能（単価・換算設定を確認）':'約¥'+Number(v).toLocaleString('ja-JP');
function analysisSummary(c){const r=analysisResults.get(c.id);return r?`<details class="analysis-cost"><summary>今回のAI利用料（概算）：${costLabel(r.estimate_jpy)}　詳細</summary><p>キャッシュ利用：${r.cache}件 ／ ローカル処理：${r.local}件 ／ AI解析：${r.ai}件</p><p>API呼出し：${r.api_calls}回 ／ 案件累計：${r.session_total?.api_calls??r.api_calls}回</p></details>`:'';}
async function checkCost(){costPlan=null;costApproved=false;if(!selectedPdfs.length||fileKinds.includes('unknown')||state.public_demo){render();return;}const epoch=queueEpoch;costChecking=true;render();try{const form=new FormData();selectedPdfs.forEach(f=>form.append('pdfs',f));form.append('kinds',JSON.stringify(fileKinds));if(route().get('case'))form.append('case_id',route().get('case'));const response=await fetch('/api/prepare-documents',{method:'POST',headers:{'X-CSRF-Token':csrf},body:form});const result=await response.json();if(!response.ok)throw Error(result.error);if(epoch===queueEpoch)costPlan=result;}catch(e){if(epoch===queueEpoch)error(e);}finally{if(epoch===queueEpoch){costChecking=false;render();if(costPlan&&!costPlan.blocked)await processUpload(route().get('case'));}}}
function requestAiConsent(){const dialog=document.querySelector('#ai-confirm');document.querySelector('#ai-confirm-text').textContent='AI解析が必要な資料：'+costPlan.ai_files+'件。概算AI料金：'+costLabel(costPlan.estimate_jpy)+'。確定請求額ではありません。選択したPDFをOpenAI APIへ送信します。';dialog.showModal();return new Promise(resolve=>{const finish=ok=>{dialog.close();resolve(ok);};document.querySelector('#ai-cancel').onclick=()=>finish(false);document.querySelector('#ai-start').onclick=()=>finish(true);dialog.oncancel=e=>{e.preventDefault();finish(false);};});}
let pdfHashes=[],pdfNotices=[],queueBusy=false,uploadBusy=false,queueEpoch=0,uploadMessage='';
const kindLabel=k=>({purchase:'購入時重要事項説明書',registry:'謄本（建物・土地）',report:'重調',rules:'管理規約',unknown:'資料種類を選択'})[k];
const inferKind=name=>/重要事項説明|購入時重説/.test(name)?'purchase':/規約|細則/.test(name)?'rules':/重調|重要事項調査/.test(name)?'report':/謄本|登記|建物|土地/.test(name)?'registry':'unknown';
function dropArea(){const disabled=state.public_demo||queueBusy||uploadBusy;return `<div class="pdf-drop ${disabled?'is-disabled':''}" data-drop-zone role="button" tabindex="${disabled?'-1':'0'}" aria-label="PDFを追加" aria-disabled="${disabled}"><strong>PDFをここにドラッグ</strong><span>または</span><span class="button primary">ファイルを選択</span><span>複数ファイル対応・購入時重説／謄本／重調／管理規約</span></div><div role="status" aria-live="polite">${queueBusy?'ファイルを確認中…':costChecking?'資料を確認中…':esc(uploadMessage)}</div>${costPlan?`<details><summary>今回のAI利用料（概算）：${costLabel(costPlan.estimate_jpy)}　詳細</summary><p>AI解析候補：${costPlan.ai_files}件</p></details>${costPlan.warning?`<p class="upload-warning">${esc(costPlan.warning)}</p>`:''}`:''}${pdfNotices.length?`<ul class="pdf-notices" role="alert">${pdfNotices.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}`;}
async function addPdfs(files){if(state.public_demo||queueBusy||uploadBusy)return;const epoch=++queueEpoch;costPlan=null;costApproved=false;costChecking=false;queueBusy=true;pdfNotices=[];uploadMessage='';render();try{for(const f of Array.from(files)){if(epoch!==queueEpoch)return;if(!/\.pdf$/i.test(f.name)){pdfNotices.push(f.name+'：PDF以外は追加できません。');continue;}const bytes=await f.arrayBuffer();if(epoch!==queueEpoch)return;const header=String.fromCharCode(...new Uint8Array(bytes.slice(0,1024)));if(!header.startsWith('%PDF-')){pdfNotices.push(f.name+'：PDF形式を確認できません。');continue;}const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');if(epoch!==queueEpoch)return;if(pdfHashes.includes(hash)){pdfNotices.push(f.name+'：同じPDFは追加済みです。');continue;}selectedPdfs.push(f);pdfHashes.push(hash);fileKinds.push(inferKind(f.name));}uploadMessage=selectedPdfs.length+'件・読取待ち';}catch(e){if(epoch===queueEpoch)pdfNotices.push('ファイルを確認できませんでした。もう一度選択してください。');}finally{if(epoch===queueEpoch){queueBusy=false;render();await checkCost();}}}
async function submitPdfs(cid){const split=!cid&&fileKinds.includes('purchase')&&fileKinds.some(k=>k!=='purchase');const indexes=selectedPdfs.map((_,i)=>i);const first=split?indexes.filter(i=>fileKinds[i]==='purchase'):indexes;const rest=split?indexes.filter(i=>fileKinds[i]!=='purchase'):[];async function send(ids,id){const form=new FormData();ids.forEach(i=>form.append('pdfs',selectedPdfs[i]));form.append('kinds',JSON.stringify(ids.map(i=>fileKinds[i])));if(id)form.append('case_id',id);form.append('plan_token',costPlan.token);form.append('ai_confirmed',String(costApproved));const response=await fetch('/api/upload-documents',{method:'POST',headers:{'X-CSRF-Token':csrf},body:form});const result=await response.json();if(!response.ok)throw Error(result.error);if(result.registration_preview)registrationPreviews.set(result.case_id,result.registration_preview);if(result.analysis_summary)analysisResults.set(result.case_id,result.analysis_summary);return result;}let result=await send(first,cid);if(rest.length){const c=result.state.cases.find(c=>c.id===result.case_id);if(!c?.registration_required&&!c?.generation_blocked){try{return {result:await send(rest,result.case_id),rest:[]};}catch(e){result.warning='購入時重説の取込は完了しました。残りの資料：'+e.message;}}else result.warning='購入時重説の取込が完了しました。案件登録・確認後、残りの資料を読み取ってください。';}return {result,rest};}
function selectedFiles(){return selectedPdfs.map((f,i)=>`<tr><td>${esc(f.name)}</td><td>${inferKind(f.name)==='unknown'?`<select aria-label="${esc(f.name)}の資料種類" data-kind="${i}" ${uploadBusy?'disabled':''}>${['unknown','purchase','registry','report','rules'].map(k=>`<option value="${k}" ${fileKinds[i]===k?'selected':''}>${kindLabel(k)}</option>`).join('')}</select>`:esc(kindLabel(fileKinds[i]))}</td><td>${uploadBusy?'アップロード中／読取中':costPlan?.files[i]?esc(costPlan.files[i].status):costChecking?'料金確認中':'読取待ち'}${costPlan?.files[i]?`<details><summary>詳細</summary><p>API利用：${costPlan.files[i].api_required?'あり':'なし'} ／ 概算：${costLabel(costPlan.files[i].estimate_jpy)}</p></details>`:''}</td><td><button data-action="remove-pdf" data-index="${i}" ${queueBusy||uploadBusy||costChecking?'disabled':''} aria-label="${esc(f.name)}を削除">削除</button></td></tr>`).join('');}
function renderDetail(c,p){p.innerHTML=`<div class="card"><h2>資料を追加</h2><p>契約書作成に使用するPDFをここへ追加してください。</p><input id="registry-pdfs" type="file" accept=".pdf,application/pdf" multiple hidden ${state.public_demo?'disabled':''}>${dropArea()}<div class="table-scroll"><table><thead><tr><th>資料名</th><th>種類</th><th>状態</th>${selectedPdfs.length?'<th>操作</th>':''}</tr></thead><tbody>${c?c.documents.flatMap(d=>(d.source_files?.length?d.source_files:[docName(d)]).map(name=>`<tr><td>${esc(name||'資料名未取得')}</td><td>${docLabel(d.type)}</td><td>読取済</td>${selectedPdfs.length?'<td></td>':''}</tr>`)).join(''):''}${selectedFiles()}</tbody></table></div>${state.public_demo?'<p>PDF追加はローカル版で利用できます。</p>':''}<div class="actions step-actions"><a class="button" href="#">案件に戻る</a>${selectedPdfs.length&&!uploadBusy&&!queueBusy&&!costChecking?'<button class="primary" data-action="read-next">解析して続ける</button>':''}${c&&!selectedPdfs.length?`<a class="button" href="${href(c.id,afterUpload(c))}">${afterUpload(c)==='review'?'要確認を開く':'契約書生成へ'}</a>`:''}<span id="upload-status" role="status"></span></div></div>`;}
const displayLabels={floor:'階',階:'階',area:'面積',面積:'面積',location:'所在',lot_number:'地番',land_category:'地目',land_area:'地積',right_type:'権利',share:'持分',numerator:'分子',denominator:'分母',rank:'順位',rank_number:'順位',type:'種類',amount:'債権額',debt_amount:'債権額',debtor:'債務者',debtors:'債務者',mortgagee:'抵当権者',creditor:'抵当権者',active:'有効',name:'氏名・名称',address:'住所',company_number:'会社法人等番号',value:'値'};
const unwrap=v=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.hasOwn(v,'value')?v.value:v;
const pick=(row,...keys)=>{for(const k of keys)if(row&&Object.hasOwn(row,k))return unwrap(row[k]);return null;};
const isReview=f=>Boolean(f.needs_review||f.evidence_mismatch||f.source_mismatch||f.source_consistent===false||(typeof f.confidence==='number'&&f.confidence<.85));
const isError=f=>Boolean(f.error||f.error_message||f.status==='error'||f.evidence_mismatch||f.source_mismatch||f.source_consistent===false);
function displayScalar(input,code=''){
 const v=unwrap(input);if(v===null||v===undefined||v==='')return '未取得';if(typeof v==='boolean')return code==='active'?(v?'有効':'無効'):(v?'有':'無');
 const text=String(v),d=text.match(/^(\d{4})-(\d{2})(?:-(\d{2}))?(?:T.*)?$/);
 if(d)return `${d[1]}年${Number(d[2])}月${d[3]?Number(d[3])+'日':''}`;
 const money=/fee$|amount|sale_price|earnest_money|債権額|金額|月額|極度額/.test(code),area=/area$|面積|地積/.test(code);
 if(typeof v==='number'||/^\d+(?:\.\d+)?$/.test(text)){
  const n=Number(v),digits=(text.split('.')[1]||'').length;
  const formatted=['house_number','lot_number','unit_name','rank'].includes(code)?text:n.toLocaleString('ja-JP',{maximumFractionDigits:Math.min(20,digits),minimumFractionDigits:Math.min(20,digits)});
  return formatted+(money?'円':area?'㎡':code==='total_units'?'戸':code==='unit_name'?'号室':code==='floor'||code==='unit_floor'?'階':'');
 }
 return text;
}
function longText(text){const more=text.length>85||text.split('\n').length>3;return `<div class="long-copy"><div class="${more?'clamped':''}">${esc(text)}</div>${more?'<button type="button" class="expand-text" data-expand aria-expanded="false">全文を見る</button>':''}</div>`;}
function shareValue(row){const share=pick(row,'share','right_share','持分','権利の割合');if(share!==null)return share;const n=pick(row,'numerator','share_numerator','持分_分子'),d=pick(row,'denominator','share_denominator','持分_分母');return n!==null&&d!==null?`${n}／${d}`:null;}
function valueTable(rows,columns,label){return `<div class="value-table-wrap"><table class="value-table" aria-label="${esc(label)}"><thead><tr>${columns.map(c=>`<th scope="col">${esc(c[0])}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${columns.map(([name,key,get])=>`<td>${formatValue(get(row),key)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function formatValue(input,code=''){
 const v=unwrap(input);
 if(Array.isArray(v)){
  if(!v.length)return '<span class="muted">該当なし</span>';
  const rows=v.map(unwrap);
  if(code==='floor_areas')return valueTable(rows,[['階','floor',r=>pick(r,'floor','階')],['面積','area',r=>pick(r,'area','面積','各階面積')]],'各階床面積');
  if(['lands','land_lots'].includes(code))return valueTable(rows,[['所在','location',r=>pick(r,'location','所在')],['地番','lot_number',r=>pick(r,'lot_number','地番')],['地目','land_category',r=>pick(r,'land_category','category','地目')],['地積','area',r=>pick(r,'area','land_area','地積')],['権利','right_type',r=>pick(r,'right_type','権利','権利の種類')],['持分','share',shareValue]],'土地一覧');
  if(['mortgages','active_mortgages'].includes(code))return valueTable(rows,[['順位','rank',r=>pick(r,'rank','rank_number','順位','順位番号')],['種類','type',r=>pick(r,'type','kind','種類')],['債権額','amount',r=>pick(r,'amount','debt_amount','債権額','極度額')],['債務者','debtor',r=>pick(r,'debtor','debtors','債務者')],['抵当権者','mortgagee',r=>pick(r,'mortgagee','creditor','抵当権者')],['状態','active',r=>pick(r,'active','有効','現在有効')]],'抵当権一覧');
  if(rows.every(x=>x&&typeof x==='object'&&!Array.isArray(x))){const keys=[...new Set(rows.flatMap(Object.keys))];return valueTable(rows,keys.map(k=>[displayLabels[k]||k,k,r=>r[k]]),'一覧');}
  return `<ul class="value-list">${rows.map(x=>`<li>${formatValue(x)}</li>`).join('')}</ul>`;
 }
 if(v&&typeof v==='object')return `<dl class="object-values">${Object.entries(v).map(([k,x])=>`<div><dt>${esc(displayLabels[k]||k)}</dt><dd>${formatValue(x,k)}</dd></div>`).join('')}</dl>`;
 return longText(displayScalar(v,code));
}
const documentGroups=[['basic','基本情報'],['lands','土地'],['rights','権利・抵当権'],['report','重調'],['review','要確認のみ']];
function fieldGroup(d,f){if(d.type==='management_rules')return 'rules';if(d.type==='important_report')return 'report';if(d.type==='purchase_important_explanation'&&/management|repair|fee|arrears|parking|pet|office|renovation|insurance|communications|trunk|association|governance|completion|total_units/.test(f.code))return 'report';if(['land_lots','lands'].includes(f.code))return 'lands';if(/mortgage|land_right|leasehold|tenure/.test(f.code))return 'rights';return 'basic';}
function fieldStatus(f){return f.accepted?'採用中':isError(f)?'根拠不一致・エラー':missing(f)?'未取得':isReview(f)?'要確認':f.approved?'✓ 確認済':'読取済';}
function evidenceRow(d,f){return `<details class="evidence-toggle"><summary>根拠</summary><div class="evidence-body"><strong>${esc(docName(d))}</strong><p>ページ：${esc(f.page_no??'未取得')} ／ 基準日：${esc(displayScalar(f.value_as_of_date))}</p>${f.source_article?`<p>条文：${esc(f.source_article)}</p>`:''}${f.source_section?`<p>${esc(f.source_section)}</p>`:''}${longText(f.source_text||'根拠テキスト未取得')}${f.candidates?.length?`<details><summary>条文候補 ${f.candidates.length}件（適用条件を確認）</summary>${f.candidates.map(x=>`<p>${esc(x.source_article)} ／ ${esc(x.page_no)}ページ</p>${longText(x.source_text)}`).join('')}</details>`:''}${f.error_message?longText(f.error_message):''}</div></details>`;}
function fieldRows(rows){return `<div class="field-head"><span>項目</span><span>値</span><span>状態</span></div>${rows.map(({d,f})=>`<article class="document-field ${isError(f)?'field-error':needs(f)?'field-review':f.approved?'field-approved':''}"><div class="field-label"><h3>${esc(f.label)}</h3></div><div class="field-value">${formatValue(f.value,f.code)}</div><div class="field-state">${pill(fieldStatus(f),needs(f))}${!f.excel_supported?'<small>Excel未対応</small>':''}${evidenceRow(d,f)}</div></article>`).join('')}${rows.length?'':'<p class="empty">該当する項目はありません。</p>'}`;}
const priority=code=>{const codes=['building_name','unit_name','house_number','registry_location','display_address','current_owner_name','registered_area','built_date','sale_price','handover_date'];const i=codes.indexOf(code);return i<0?99:i;};
function renderDocuments(c,p){const group=filters.group||'basic';const rows=fields(c).filter(({d,f})=>group==='landrights'?['lands','rights'].includes(fieldGroup(d,f)):fieldGroup(d,f)===group).filter(({d,f})=>(filters.document==='all'||d.version_id===filters.document)&&(!filters.review||needs(f)));p.innerHTML=`<div class="card document-card"><h2>読取内容の確認</h2>${c.registration_required?`<p>読取は完了しました。Excel生成前に<a href="${href(c.id)}">物件・資料で案件登録</a>を行ってください。</p>`:''}<p>この画面でやること：読み取った内容を確認してください。</p><p class="next-task">次にやること：物件名・号室・家屋番号・所在・所有者・面積・売買代金・引渡日を確認してください。</p><p>要確認が${reviewCount(c)}件あります。</p><nav class="document-tabs" aria-label="確認する情報">${[['registry','basic','建物・住戸'],['lands','landrights','土地・権利'],['report','report','管理・費用'],['rules','rules','管理規約']].map(([t,g,label])=>`<a class="button ${group===g?'selected':''}" href="${href(c.id,t)}" ${group===g?'aria-current="page"':''}>${label}</a>`).join('')}</nav><div class="toolbar"><label>資料 <select id="document-filter"><option value="all">すべての資料</option>${c.documents.map(d=>`<option value="${esc(d.version_id)}" ${filters.document===d.version_id?'selected':''}>${esc(docName(d))}</option>`).join('')}</select></label><label><input id="review-filter" type="checkbox" ${filters.review?'checked':''}> 要確認のみ</label></div>${fieldRows(group==='basic'?[...rows].sort((a,b)=>priority(a.f.code)-priority(b.f.code)):rows)}<div class="actions step-actions"><a class="button" href="${href(c.id)}">資料へ戻る</a><a class="button primary" href="${href(c.id,'review')}">要確認・差分へ進む</a></div></div>`;}
function renderReview(c,p){p.innerHTML=`<div class="card"><h2>確認が必要な項目</h2><p>${blocking(c)?'生成に必要な情報を確認してください。':reviewCount(c)?'使用する値を選んでください。':'契約書を生成できます。'}</p>${c.generation_blocked?'<p class="upload-warning">物件種別・資料の対応が確定していないため生成できません。</p>':''}${c.registration_required?registrationPanel(c):''}${c.id.startsWith('upload-purchase-')&&blocking(c)?`<details><summary>必須情報を原本で確認・入力</summary>${purchaseReviewPanel(c)}</details>`:''}${c.pending_documents?.length?pendingPanel(c):''}${conflictPanel(c)}<div id="diff-panel"></div><div class="actions"><a href="${href(c.id)}">資料を追加する</a>${!blocking(c)?`<a class="button primary" href="${href(c.id,'excel')}">契約書生成へ</a>`:''}</div></div>`;renderDiffs(c,document.querySelector('#diff-panel'));}
function renderDiffs(c,p){p.innerHTML=unresolvedDiffs(c).map(d=>`<section class="card"><h3>${esc(d.label)}</h3><div class="diff-values"><div>旧<p>${formatValue(d.old_value,d.code)}</p></div><span>→</span><div>新<p>${formatValue(d.new_value,d.code)}</p></div></div><details><summary>原文を見る</summary><p>${esc(d.source||'根拠資料の確認が必要')}</p></details><div class="actions"><button data-action="use-old" data-diff="${esc(d.id)}">旧を使う</button><button class="primary" data-action="adopt" data-diff="${esc(d.id)}" ${!d.can_adopt?'disabled':''}>新を使う</button>${!d.can_adopt?'<span>新しい値は原本確認が必要です。</span>':''}</div></section>`).join('');}
function renderExcel(c,p){const r=results.get(c.id);p.innerHTML=`<div class="card"><h2>契約書を生成</h2><p>対象：${esc(c.building_name)} ${esc(c.unit_name||'')}</p>${blocking(c)?`<p class="upload-warning">生成不可：必須事項を確認してください。</p><a href="${href(c.id,'review')}">要確認を開く</a>`:''}${state.public_demo?'<p>Excel生成はローカル版で利用できます。</p>':''}${r?`<p>契約書を作成しました。</p><a class="button primary" href="${esc(r.download)}" download>Excelをダウンロード</a><p><a href="${href(c.id)}">資料を追加する</a></p>`:`<button class="primary" data-action="generate" ${state.public_demo||blocking(c)?'disabled':''}>契約書Excelを生成</button>`}</div>`;}

function purchaseReviewPanel(c){const doc=c.documents.find(d=>d.type==='purchase_important_explanation');return `<div class="card"><h2>スキャン原本の確認・訂正</h2><p>購入時点の原文と照合し、確認した項目だけチェックしてください。PDFの先頭を1ページとして数えます。AIの自信が高くても誤読することがあります。</p><label>原本で確認した物件種別 <select id="purchase-property-type">${[['unknown','判定不能'],['condominium_land_right','区分マンション・敷地権あり'],['condominium_no_land_right','区分マンション・敷地権なし'],['leasehold_condominium','借地マンション'],['detached_house','戸建て（対象外）']].map(([v,l])=>`<option value="${v}" ${v===c.property_type?'selected':''}>${l}</option>`).join('')}</select></label><details><summary>抽出値を原本と照合する</summary>${doc.fields.map(f=>`<section data-purchase-field="${esc(f.code)}"><h3>${esc(f.label)}</h3><label><input type="checkbox" data-verified> この項目を原本で確認した</label>${purchaseValueEditor(f)}<label>PDFページ <input type="number" min="1" data-page value="${esc(f.page_no||'')}"></label><label>基準日 <input type="date" data-asof value="${esc(f.value_as_of_date||'')}"></label><label>原文 <textarea data-quote>${esc(f.source_text||'')}</textarea></label></section>`).join('')}</details><button data-action="verify-purchase">原本確認した内容を保存</button></div>`;}
function purchaseValueEditor(f){if(['land_lots','active_mortgages'].includes(f.code)){const keys=f.code==='land_lots'?['location','lot_number','land_category','area','right_type','numerator','denominator']:['rank','type','amount','debtor','mortgagee','active'];const rows=Array.isArray(f.value)&&f.value.length?f.value:[{}];return `<div class="table-scroll"><table><thead><tr>${keys.map(k=>`<th>${esc(displayLabels[k]||k)}</th>`).join('')}</tr></thead><tbody>${rows.map((r,i)=>`<tr>${keys.map(k=>`<td><input data-array-key="${k}" data-row="${i}" value="${esc(r[k]??'')}" aria-label="${esc(displayLabels[k]||k)}"></td>`).join('')}</tr>`).join('')}</tbody></table><p>空欄の行は保存しません。有無は true / false、面積・分子・分母は数値です。</p></div>`;}return `<label>内容 <input data-value value="${esc(f.value??'')}" aria-label="${esc(f.label)}"></label>`;}
function purchaseEntries(){return Array.from(document.querySelectorAll('[data-purchase-field]')).filter(el=>el.querySelector('[data-verified]').checked).map(el=>{const code=el.dataset.purchaseField;let value;if(['land_lots','active_mortgages'].includes(code)){const rows={};el.querySelectorAll('[data-array-key]').forEach(input=>{let v=input.value.trim(),k=input.dataset.arrayKey;if(!v)v=null;else if(['area','numerator','denominator'].includes(k)){v=Number(v);if(!Number.isFinite(v))throw Error('数値を確認してください。');}else if(k==='active'){if(!['true','false'].includes(v))throw Error('有効状態はtrueまたはfalseです。');v=v==='true';}(rows[input.dataset.row]??={})[k]=v;});value=Object.values(rows).filter(r=>Object.values(r).some(v=>v!==null));}else{value=el.querySelector('[data-value]').value.trim();if(['registered_area','land_right_numerator','land_right_denominator','total_units','management_fee','repair_reserve_fee','wall_center_area','sale_price','earnest_money'].includes(code)){if(!value)throw Error('確認する数値を入力してください。');value=Number(value);if(!Number.isFinite(value))throw Error('数値を確認してください。');}else if(code==='has_land_right'){if(!['true','false'].includes(value))throw Error('敷地権の有無はtrueまたはfalseです。');value=value==='true';}else value=value||null;}return {code,value,verified:true,page_no:Number(el.querySelector('[data-page]').value),source_text:el.querySelector('[data-quote]').value,value_as_of_date:el.querySelector('[data-asof]').value||null};});}

function registrationPanel(c){const r=registrationPreviews.get(c.id);return `<div class="card"><h2>案件登録</h2><p>自動登録できない理由と候補を確認してください。</p><button data-action="registration-preview" ${c.generation_blocked?'disabled':''}>照合を再試行</button>${r?`<dl class="facts">${[['building_name','物件名'],['unit_name','号室'],['house_number','家屋番号'],['registry_location','登記所在'],['current_owner_name','所有者']].map(([k,l])=>`<div><dt>${l}</dt><dd>${esc(r.summary[k]??'未取得')}</dd></div>`).join('')}</dl><h3>既存候補</h3>${r.match.candidates?.length?`<div class="table-scroll"><table><thead><tr><th>物件名</th><th>号室</th><th>家屋番号</th><th>所在</th><th>所有者</th><th>操作</th></tr></thead><tbody>${r.match.candidates.map(x=>`<tr><td>${esc(x.building_name||'未取得')}</td><td>${esc(x.unit_name||'—')}</td><td>${esc(x.house_number||'—')}</td><td>${esc(x.registry_location||'—')}</td><td>${esc(x.current_owner_name||'—')}</td><td>${r.match.status==='ambiguous'?`<button data-action="select-candidate" data-candidate="${esc(x.unit_id||x.building_id)}">この物件を使う</button>`:''}</td></tr>`).join('')}</tbody></table></div>`:'<p>候補はありません。</p>'}<p>${esc(r.message||r.match.reason|| (r.match.status==='existing'?'既存住戸へ紐付けます。':'新規の物件・住戸を登録します。'))}</p>${['new','existing'].includes(r.match.status)&&!r.demo?`<label>案件の扱い <select id="registration-case-mode">${(r.match.cases||[]).map(x=>`<option value="resume:${esc(x.case_id)}">既存案件を再開（${esc(x.case_status)} / ${esc(x.updated_at||'更新日不明')}）</option>`).join('')}<option value="new">新しい案件を作成</option></select></label><div class="actions"><button class="primary" data-action="register-case">この案件で登録</button></div>`:'<p class="pill warn">要確認：この状態では登録しません。</p>'}`:''}</div>`;}

view.addEventListener('dragover',e=>{const z=e.target.closest('[data-drop-zone]');if(!z)return;e.preventDefault();if(!state.public_demo&&!queueBusy&&!uploadBusy)z.classList.add('is-dragging');});
view.addEventListener('dragleave',e=>{const z=e.target.closest('[data-drop-zone]');if(z&&!z.contains(e.relatedTarget))z.classList.remove('is-dragging');});
view.addEventListener('drop',e=>{const z=e.target.closest('[data-drop-zone]');if(!z)return;e.preventDefault();z.classList.remove('is-dragging');return addPdfs(e.dataTransfer.files);});
view.addEventListener('keydown',e=>{const z=e.target.closest('[data-drop-zone]');if(z&&['Enter',' '].includes(e.key)){e.preventDefault();if(!state.public_demo&&!queueBusy&&!uploadBusy)document.querySelector('#registry-pdfs').click();}});
view.addEventListener('change',e=>{if(e.target.id==='registry-pdfs'){addPdfs(e.target.files);return;}if(e.target.dataset.kind!==undefined){fileKinds[Number(e.target.dataset.kind)]=e.target.value;queueEpoch++;checkCost();return;}if(e.target.id==='mapping-filter'){mappingFilter=e.target.value;renderMapping();return;}if(e.target.id==='case-filter'){caseFilter=e.target.value;location.hash='#list='+caseFilter;renderList();return;}if(e.target.id==='case-search'){caseSearch=e.target.value;renderList();return;}if(!['document-filter','review-filter'].includes(e.target.id))return;if(e.target.id==='document-filter')filters.document=e.target.value;if(e.target.id==='review-filter')filters.review=e.target.checked;render();});
view.addEventListener('click',async e=>{const expand=e.target.closest('[data-expand]');if(expand){const open=expand.getAttribute('aria-expanded')!=='true';expand.setAttribute('aria-expanded',String(open));expand.previousElementSibling.classList.toggle('clamped',!open);expand.textContent=open?'閉じる':'全文を見る';return;}const group=e.target.closest('[data-group]');if(group){filters.group=group.dataset.group;filters.document='all';filters.review=false;render();return;}const zone=e.target.closest('[data-drop-zone]');if(zone){if(!state.public_demo&&!queueBusy&&!uploadBusy)document.querySelector('#registry-pdfs').click();return;}const b=e.target.closest('button[data-action]');if(!b)return;const action=b.dataset.action,cid=route().get('case');document.querySelector('#error').textContent='';
 if(action==='use-old'||action==='use-conflict'){b.disabled=true;try{state=await api('/api/choice',{case_id:cid,kind:action==='use-old'?'diff':'conflict',key:action==='use-old'?b.dataset.diff:b.dataset.key,source:action==='use-old'?'old':b.dataset.source});results.delete(cid);render();}catch(e){error(e);b.disabled=false;}return;}
 if(action==='verify-purchase'){try{let result=await api('/api/verify-purchase',{case_id:cid,fields:purchaseEntries(),property_type:document.querySelector('#purchase-property-type').value});result=await api('/api/auto-register',{case_id:cid});state=result.state;if(result.registration_preview)registrationPreviews.set(cid,result.registration_preview);else registrationPreviews.delete(cid);uploadScope=result.case_id;location.hash=href(result.case_id,afterUpload(state.cases.find(c=>c.id===result.case_id)));render();if(result.warning)error(Error(result.warning));}catch(e){error(e);}return;}
 if(action==='select-candidate'){b.disabled=true;try{const r=registrationPreviews.get(cid);const result=await api('/api/select-candidate',{token:r.token,candidate_id:b.dataset.candidate});state=result.state;if(result.registration_preview)registrationPreviews.set(cid,result.registration_preview);else registrationPreviews.delete(cid);uploadScope=result.case_id;location.hash=href(result.case_id,afterUpload(state.cases.find(c=>c.id===result.case_id)));render();if(result.warning)error(Error(result.warning));}catch(e){error(e);b.disabled=false;}return;}
 if(action==='select-purchase'){document.querySelector('#registry-pdfs').click();return;}
 if(action==='registration-preview'||action==='register-case'){b.disabled=true;try{if(action==='registration-preview'){const result=await api('/api/auto-register',{case_id:cid});state=result.state;if(result.registration_preview)registrationPreviews.set(cid,result.registration_preview);if(result.case_id!==cid){uploadScope=result.case_id;location.hash=href(result.case_id,afterUpload(state.cases.find(c=>c.id===result.case_id)));}render();if(result.warning)error(Error(result.warning));}else{const r=registrationPreviews.get(cid),mode=document.querySelector('#registration-case-mode').value;const result=await api('/api/register-case',{token:r.token,case_mode:mode==='new'?'new':'resume',resume_case_id:mode.startsWith('resume:')?mode.slice(7):null});state=result.state;registrationPreviews.delete(cid);uploadScope=result.case_id;location.hash=href(result.case_id,selectedPdfs.length?'detail':afterUpload(state.cases.find(c=>c.id===result.case_id)));render();if(result.warning)error(Error(result.warning));}}catch(e){error(e);b.disabled=false;}return;}
 if(action==='retry-documents'){b.disabled=true;try{const result=await api('/api/retry-documents',{case_id:cid});state=result.state;render();if(result.warning)error(Error(result.warning));}catch(e){error(e);b.disabled=false;}return;}
 if(action==='remove-pdf'){if(!queueBusy&&!uploadBusy){const i=Number(b.dataset.index);selectedPdfs.splice(i,1);fileKinds.splice(i,1);pdfHashes.splice(i,1);uploadMessage=selectedPdfs.length+'件・読取待ち';queueEpoch++;render();await checkCost();}return;}
 if(action==='select-pdf'){if(queueBusy||uploadBusy)return;document.querySelector('#registry-pdfs').click();return;}
 if(action==='read-next'&&!selectedPdfs.length&&cid){location.hash=href(cid,afterUpload(state.cases.find(c=>c.id===cid)));return;}
 if(action==='upload'||action==='read-next'){await processUpload(cid);return;}
 if(action==='adopt'){b.disabled=true;try{state=await api('/api/decision',{case_id:cid,diff_id:b.dataset.diff,action:'adopt'});results.delete(cid);render();}catch(e){error(e);b.disabled=false;}return;}
 b.disabled=true;const old=b.textContent;if(action==='generate')b.textContent='契約書作成中…';
 try{if(action==='generate')results.set(cid,await api('/api/generate',{case_id:cid}));else if(action==='hold')state=await api('/api/decision',{case_id:cid,diff_id:b.dataset.diff,action:'hold'});else if(action==='refresh')state=await api('/api/refresh',{});render();}catch(e){error(e);b.disabled=false;b.textContent=old;}
});
document.querySelector('#cancel').onclick=()=>document.querySelector('#confirm').close();
document.querySelector('#accept').onclick=async()=>{const b=document.querySelector('#accept');b.disabled=true;try{state=await api('/api/decision',pending);results.delete(pending.case_id);document.querySelector('#confirm').close();render();}catch(e){document.querySelector('#confirm').close();error(e)}finally{b.disabled=false}};
let uploadScope='';
window.addEventListener('hashchange',()=>{const scope=route().get('case')||route().get('source')||'';if(scope!==uploadScope&&!uploadBusy){selectedPdfs=[];fileKinds=[];pdfHashes=[];pdfNotices=[];costPlan=null;costApproved=false;costChecking=false;queueEpoch++;queueBusy=false;uploadMessage='';uploadScope=scope;}});
window.addEventListener('hashchange',()=>{document.querySelector('#error').textContent='';filters.document='all';filters.review=false;render()});
api('/api/state').then(d=>{state=d;csrf=d.csrf;render()}).catch(error);

function pendingPanel(c){return `<div class="card"><h3>登録待ちの追加資料</h3><table><thead><tr><th>資料名</th><th>種類</th><th>状態</th></tr></thead><tbody>${c.pending_documents.map(f=>`<tr><td>${esc(f.filename)}</td><td>${f.kind==='rules'?'管理規約':'重調'}</td><td>未保存</td></tr>`).join('')}</tbody></table>${!c.registration_required?'<button data-action="retry-documents">追加資料の保存を再実行</button>':'<p>「この案件で登録」の後に読み取り・保存します。</p>'}</div>`;}
function conflictPanel(c){return unresolvedConflicts(c).map(x=>`<section class="card"><h3>${esc(x.label)}</h3><div class="diff-values"><div>重調<p>${formatValue(x.report_value,x.code)}</p><button data-action="use-conflict" data-key="${esc(x.choice_id)}" data-source="report">重調の値を使う</button></div><span>／</span><div>管理規約<p>${formatValue(x.rules_value,x.code)}</p><button data-action="use-conflict" data-key="${esc(x.choice_id)}" data-source="rules">管理規約の値を使う</button></div></div><details><summary>原文を見る</summary><p>${esc(x.report_document)} ／ ${esc(x.rules_document)}</p>${fieldRows(fields(c).filter(({f})=>f.code===x.code||x.code==='parking_rules'&&f.code==='parking_facility_info'))}</details></section>`).join('');}

function uploadInstruction(){if(uploadBusy)return '資料の読取・案件照合を行っています。';if(costChecking||queueBusy)return '資料を確認しています。';if(fileKinds.includes('unknown'))return '判定できなかった資料の種類を選択してください。';if(costPlan?.blocked)return costPlan.warning;if(costPlan?.ai_files)return 'AI解析を開始してください。';return 'PDFを追加してください。';}

async function processUpload(cid){if(queueBusy||uploadBusy||costChecking)return;if(!selectedPdfs.length||fileKinds.includes('unknown')){error(Error('PDFと各資料種類を選択してください。'));return;}if(!costPlan){await checkCost();return;}if(costPlan.blocked){error(Error(costPlan.warning));return;}if(costPlan.ai_files&&!costApproved){uploadBusy=true;const epoch=queueEpoch;costApproved=await requestAiConsent();uploadBusy=false;if(!costApproved||epoch!==queueEpoch){costApproved=false;return;}}uploadBusy=true;pdfNotices=[];uploadMessage='アップロード中／読取中…完了までお待ちください。';render();document.querySelector('#upload-status').textContent=uploadMessage;try{const submitted=await submitPdfs(cid);const result=submitted.result;state=result.state;selectedPdfs=submitted.rest.map(i=>selectedPdfs[i]);fileKinds=submitted.rest.map(i=>fileKinds[i]);pdfHashes=submitted.rest.map(i=>pdfHashes[i]);costPlan=null;costApproved=false;uploadBusy=false;uploadMessage=selectedPdfs.length?'残り'+selectedPdfs.length+'件・読取待ち':'完了：資料を読み取りました。';uploadScope=result.case_id;const imported=state.cases.find(c=>c.id===result.case_id);location.hash=href(result.case_id,selectedPdfs.length?'detail':afterUpload(imported));render();if(result.warning)error(Error(result.warning));}catch(e){costPlan=null;costApproved=false;uploadBusy=false;uploadMessage='エラー：読み取れませんでした。資料を確認して再実行してください。';render();error(e);const status=document.querySelector('#upload-status');if(status)status.textContent=uploadMessage;}return;}

function adoptLabel(d){const source=d.source||'';return source.includes('謄本')?'最新謄本を採用':source.includes('重調')||source.includes('調査報告')?'最新重調を採用':'新しい値を採用';}

let mappingRows=null,mappingFilter='all';
async function renderMapping(){view.innerHTML='<h1>Excelマッピング</h1><p>読込中…</p>';try{if(!mappingRows)mappingRows=(await api('/api/mapping')).rows;if(!route().has('mapping'))return;const yes=mappingRows.filter(r=>r.excel_supported).length,rows=mappingRows.filter(r=>mappingFilter==='all'||r.excel_supported===(mappingFilter==='yes'));view.innerHTML=`<h1>Excelマッピング</h1><p>取得可能項目（資料別）：${mappingRows.length}件 ／ Excel対応済み：${yes}件 ／ Excel未対応：${mappingRows.length-yes}件</p><div class="toolbar"><label>表示 <select id="mapping-filter">${[['all','すべて'],['yes','Excel対応済み'],['no','Excel未対応']].map(([v,l])=>`<option value="${v}" ${mappingFilter===v?'selected':''}>${l}</option>`).join('')}</select></label><a class="button" href="/api/mapping.csv" download>マッピング一覧をCSV出力</a></div><div class="table-scroll"><table><thead><tr>${['field_code','日本語名','entity_level','primary_source','Supabase保存','Excel対応','excel_named_range','シート','セル','備考'].map(k=>`<th>${k}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${['field_code','label','entity_level','primary_source','db_supported','excel_supported','excel_named_range','sheet','cell','notes'].map(k=>`<td>${esc(typeof r[k]==='boolean'?(r[k]?'対応済み':'未対応'):r[k]||'—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}catch(e){view.innerHTML='<h1>Excelマッピング</h1>';error(e);}}
